В try catch конструкцию завернуть код: console.log(a), let a = 3. И вывести ошибку – ‘let перед использованием нужно объявить’. При выполнении 1/0  выводить ошибку 'на ноль делить нельзя'

try {
console.log(a);
let a = 3
} catch (e) {
console.log('let перед использованием нужно объявить');
}

function error(a) {
try {
if (a === 0) {
throw new Error("на ноль делить нельзя")
}
return 1 / a;
} catch (e) {
console.log(e.message)
}
}
